"""added table share reactions

Revision ID: 0e99a331fa4b
Revises: f3707f3fbebc
Create Date: 2025-11-13 20:06:48.018017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e99a331fa4b'
down_revision: Union[str, Sequence[str], None] = 'f3707f3fbebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_post_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['shared_post_id'], ['shared_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shared_post_id', 'user_id', name='unique_shared_post_reaction')
    )
    op.add_column('shared_posts', sa.Column('reaction_cnt', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shared_posts', 'reaction_cnt')
    op.drop_table('shared_post_reactions')
    # ### end Alembic commands ###
