"""new col added to track a reply msg

Revision ID: 41c7b226f3fd
Revises: af0f82c54009
Create Date: 2025-11-14 18:27:56.753570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c7b226f3fd'
down_revision: Union[str, Sequence[str], None] = 'af0f82c54009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_reply_msg', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_reply_msg')
    # ### end Alembic commands ###
