"""added col to store msg reactions

Revision ID: 83c3b691de9c
Revises: 5caaa185310a
Create Date: 2025-11-12 19:14:04.734724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c3b691de9c'
down_revision: Union[str, Sequence[str], None] = '5caaa185310a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reaction', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reaction')
    # ### end Alembic commands ###
