"""add shared post replies table and is_reply_to_share flag

Revision ID: 9537c9b62a58
Revises: b260b2535f09
Create Date: 2025-11-19 11:19:05.034982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9537c9b62a58'
down_revision: Union[str, Sequence[str], None] = 'b260b2535f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
