"""new col added to Message table

Revision ID: a8c917fb0dfe
Revises: 8c3816dff3c5
Create Date: 2025-11-09 21:43:00.288206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c917fb0dfe'
down_revision: Union[str, Sequence[str], None] = '8c3816dff3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_deleted_for_everyone', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_deleted_for_everyone')
    # ### end Alembic commands ###
