"""fk constraints altered

Revision ID: ae5000d4c5a2
Revises: 8d516c168db3
Create Date: 2025-11-02 15:33:40.705339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5000d4c5a2'
down_revision: Union[str, Sequence[str], None] = '8d516c168db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('connections_follower_id_fkey'), 'connections', type_='foreignkey')
    op.drop_constraint(op.f('connections_followed_id_fkey'), 'connections', type_='foreignkey')
    op.create_foreign_key(None, 'connections', 'users', ['followed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'connections', 'users', ['follower_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('post_views_user_id_fkey'), 'post_views', type_='foreignkey')
    op.drop_constraint(op.f('post_views_post_id_fkey'), 'post_views', type_='foreignkey')
    op.create_foreign_key(None, 'post_views', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_views', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_views', type_='foreignkey')
    op.drop_constraint(None, 'post_views', type_='foreignkey')
    op.create_foreign_key(op.f('post_views_post_id_fkey'), 'post_views', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(op.f('post_views_user_id_fkey'), 'post_views', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.create_foreign_key(op.f('connections_followed_id_fkey'), 'connections', 'users', ['followed_id'], ['id'])
    op.create_foreign_key(op.f('connections_follower_id_fkey'), 'connections', 'users', ['follower_id'], ['id'])
    # ### end Alembic commands ###
