"""message replies table added

Revision ID: af0f82c54009
Revises: 0e99a331fa4b
Create Date: 2025-11-14 17:07:03.619943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af0f82c54009'
down_revision: Union[str, Sequence[str], None] = '0e99a331fa4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_replies',
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reply_id', 'original_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_replies')
    # ### end Alembic commands ###
