"""added two cols media_type and media_ur;

Revision ID: b1b5e7c1b277
Revises: c7f7bb7b86ea
Create Date: 2025-11-19 16:08:06.502786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b5e7c1b277'
down_revision: Union[str, Sequence[str], None] = 'c7f7bb7b86ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('media_url', sa.String(), server_default='false', nullable=True))
    op.add_column('messages', sa.Column('media_type', sa.String(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'media_type')
    op.drop_column('messages', 'media_url')
    # ### end Alembic commands ###
