"""is read col added

Revision ID: e1bc9340f82d
Revises: 245d3c8d5b59
Create Date: 2025-11-09 13:56:34.275589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bc9340f82d'
down_revision: Union[str, Sequence[str], None] = '245d3c8d5b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_posts', sa.Column('is_read', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shared_posts', 'is_read')
    # ### end Alembic commands ###
