"""added table message reactions

Revision ID: f3707f3fbebc
Revises: 83c3b691de9c
Create Date: 2025-11-13 16:18:44.013615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3707f3fbebc'
down_revision: Union[str, Sequence[str], None] = '83c3b691de9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='unique_user_reaction')
    )
    op.add_column('messages', sa.Column('reaction_cnt', sa.Integer(), server_default='0', nullable=True))
    op.drop_column('messages', 'reaction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reaction', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'reaction_cnt')
    op.drop_table('message_reactions')
    # ### end Alembic commands ###
