"""new col added to SharedPosts table

Revision ID: f8ebff38e6fc
Revises: a8c917fb0dfe
Create Date: 2025-11-11 15:29:28.973628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ebff38e6fc'
down_revision: Union[str, Sequence[str], None] = 'a8c917fb0dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_posts', sa.Column('is_deleted_for_everyone', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shared_posts', 'is_deleted_for_everyone')
    # ### end Alembic commands ###
